### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SRLJustin** [l2-/template-plugin#44]
2022-10-23 09:05:29 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at com.xpdrops.overlay.TextComponentWithAlpha.render(TextComponentWithAlpha.java:63)
	at com.xpdrops.overlay.XpDropOverlayUtilities.drawText(XpDropOverlayUtilities.java:192)
	at com.xpdrops.overlay.XpDropOverlay.drawXpDrops(XpDropOverlay.java:96)
	at com.xpdrops.overlay.XpDropOverlay.render(XpDropOverlay.java:40)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:719)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:322)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderAfterInterface(OverlayRenderer.java:236)
	at net.runelite.client.callback.Hooks.drawInterface(Hooks.java:522)
	at client.ov(client.java:541)
	at jd.jk(jd.java:10789)
	at ao.jn(ao.java:10296)
	at client.ho(client.java:4495)
	at client.av(client.java:1215)
	at ae.aj(ae.java:415)
	at ae.run(ae.java:369)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by l2-** [comment]
Should be fixed in https://github.com/runelite/plugin-hub/pull/3486.

**Comment by SRLJustin** [comment]
thanks boss
