### ISSUE TITLE
xp tracker not displaying 

### ISSUE THREAD

**Issue by j0esmama32** [l2-/template-plugin#71]
xp tracker is currently not displaying when the plugin is enabled. 
all other portions of the plugin are working. 
unsure if its a compatibility issue with another plugin, it only happened today and I have not added new or made any changes myself to any plugins. 

log data below

2023-07-02 08:56:58 AEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: Index 22 out of bounds for length 22
	at com.xpdrops.CustomizableXpDropsPlugin.onStatChanged(CustomizableXpDropsPlugin.java:396)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:191)
	at client.uk(client.java:10155)
	at client.jy(client.java:56981)
	at client.hi(client.java:3109)
	at client.bz(client.java:1139)
	at ba.bo(ba.java:382)
	at ba.run(ba.java:361)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-07-02 08:57:02 AEST [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at com.xpdrops.overlay.XpTrackerOverlay.getSkillExperience(XpTrackerOverlay.java:80)
	at com.xpdrops.overlay.XpTrackerOverlay.render(XpTrackerOverlay.java:54)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:735)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
	at net.runelite.client.callback.Hooks.drawAboveOverheads(Hooks.java:499)
	at jp.bk(jp.java:36861)
	at jp.ak(jp.java:122)
	at ir.ii(ir.java:4989)
	at gr.kp(gr.java:10660)
	at gr.kp(gr.java:10691)
	at im.ke(im.java:10555)
	at client.ie(client.java:4646)
	at client.bb(client.java:1175)
	at ba.az(ba.java:408)
	at ba.run(ba.java:362)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by l2-** [comment]
Fixed when https://github.com/runelite/plugin-hub/pull/4573 is merged.
