### ISSUE TITLE
No XP drop for Construction skill

### ISSUE THREAD

**Issue by draghar** [l2-/template-plugin#72]
I am getting exp drops for other things, just not construction.  I've restarted runelite with cleared cache and nothing changed. I could revert setting, but don't really want to set it back up at the moment and I don't feel it'd help,  I DO get the default exp drops for construction with the plugin disabled.

A solution would be welcome, but this is mostly to report the issue.

This is the only error thing from the logs that looks relevant to this plugin.

2023-07-01 19:04:25 MDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: Index 22 out of bounds for length 22
	at com.xpdrops.CustomizableXpDropsPlugin.onStatChanged(CustomizableXpDropsPlugin.java:396)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:191)
	at client.uk(client.java:10155)
	at client.jy(client.java:56981)
	at client.hi(client.java:3109)
	at client.bz(client.java:1139)
	at ba.bo(ba.java:382)
	at ba.run(ba.java:361)
	at java.base/java.lang.Thread.run(Unknown Source)
	
	
![magic exp drop](https://github.com/l2-/template-plugin/assets/40870048/c5a96bc8-0e10-497c-822f-d228ee3db460)
![no constr exp](https://github.com/l2-/template-plugin/assets/40870048/db45e1f1-c82c-4d3f-ba03-7a9166b12613)
![xp addons](https://github.com/l2-/template-plugin/assets/40870048/7d72f8e6-0e3c-4204-9bc7-10bf57b3dd57)
![xp settings](https://github.com/l2-/template-plugin/assets/40870048/1402b834-9980-4705-84ff-58d0fa1ffe25)

**Comment by McFrosty420** [comment]
I am also having this problem also

**Comment by l2-** [comment]
Fixed when https://github.com/runelite/plugin-hub/pull/4573 is merged
